### ISSUE TITLE
报错信息: 'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by GerrryX** [LINKlang/SillyTavern-Clewd-auto#2]
**标题:** 更新cookie时出现问题

**触发位置:**正在修改clewd.js

**截图:** ![image](https://github.com/LINKlang/SillyTavern-Clewd-auto/assets/126783929/e0e57e53-c9cb-43b3-b0a6-5dd78bbb1703)

**报错:** 'NoneType' object has no attribute 'append'

**模式:** [模式1]

**版本:** [3.5.3]

**环境:** [Windows11]

**Comment by LINKlang** [comment]
发一下详细报错

**Comment by LINKlang** [comment]
长时间未回复，故作已解决处理
