### ISSUE TITLE
邮箱注册登录失败

### ISSUE THREAD

**Issue by sico197** [LINKlang/SillyTavern-Clewd-auto#3]
启动Chrome浏览器
请输入一个邮箱并按下回车：
等待发送验证码
请输入邮箱中收到的验证码: 

⚠⚠⚠ 元素 //button[contains(normalize-space(), "Continue with login code")] 模式 移动点击 定位失败，正在第 1 次重试

⚠⚠⚠ 元素 //button[contains(normalize-space(), "Continue with login code")] 模式 移动点击 定位失败，正在第 2 次重试

⚠⚠⚠ 元素 //button[contains(normalize-space(), "Continue with login code")] 模式 移动点击 定位失败，正在第 3 次重试
已保存报错前浏览器截图到screenshot文件夹
查看过截图后自行判断是否尝试直接提取cookie（y/N）:

**Comment by LINKlang** [comment]
3.5.4版本修复
