### ISSUE TITLE
手机验证码以及大面积的白屏

### ISSUE THREAD

**Issue by Xier-no1** [LINKlang/SillyTavern-Clewd-auto#5]
问题1：在注册时哪怕我本人接收到验证码也会显示“手机号错误, 请重新检查后重新输入, 在手机号正确的情况下还出现此报错, 建议退款后重新购买新的手机号”我尝试用其他手机号也一样
问题2：在请选择使用的浏览器时选择Chrome会有大面积的白屏可是不会影响点击桌面其他快捷方式以及哪怕把“一键开启Claude酒馆之门.exe”关闭也会残留只有在任务管理器结束Google Chrome才会消失

![屏幕截图 2024-10-15 122743](https://github.com/user-attachments/assets/7c294e6e-b076-4151-8d06-edcecc75be28)

![屏幕截图 2024-10-15 123612](https://github.com/user-attachments/assets/eb49f613-a6c6-42f5-830a-8ec6087aa94b)

使用时的模式为模式1

使用时的版本为3.6.0

使用时的系统环境为Windows11

**Comment by LINKlang** [comment]
你好，请尝试打开脚本路径下的.env文件，插入一行
Debug='True'
然后重新尝试方法1（确保使用同一邮箱排除账号问题），如果同样出现问题，将所有输出保存到一个文本文档里，发送至该issue，检查screenshot文件夹下有没有当前日期的png和html文件，若有，请和文本文档一同发送

**Comment by LINKlang** [comment]
已修复
