### ISSUE TITLE
登录报错'NoneType' object has no attribute 'append'提示需要手动添加cookie，选择添加cookie后就报错然后闪退

### ISSUE THREAD

**Issue by duduxx123** [LINKlang/SillyTavern-Clewd-auto#6]
**标题:** 登录报错与添加cookie报错

**触发位置:** [登录与添加cookie]

**截图:** ![image](https://github.com/user-attachments/assets/4d10dba9-d579-43db-beb3-30c6e5ae6ff0)
![image](https://github.com/user-attachments/assets/0ab112e3-6e9d-4dd2-b2a7-5138308f1191)

**报错:** [更新cookie时出现问题
报错信息: 'NoneType' object has no attribute 'append'
请复制后发给作者(3185774357)
显示详细报错？(发送报错给作者时使用)
y/N: y
本次获取到的cookie, 请手动添加]

**模式:** [模式1]

**版本:** [3.7.2]
**环境:** [Windows11]

**Comment by LINKlang** [comment]
未能复现错误，由于没有详细报错无法分析问题，若问题依旧存在，请联系作者qq

**Comment by duduxx123** [comment]
> 未能复现错误，由于没有详细报错无法分析问题，若问题依旧存在，请联系作者qq

作者你好，能提供下qq吗

**Comment by LINKlang** [comment]
> > 未能复现错误，由于没有详细报错无法分析问题，若问题依旧存在，请联系作者qq
> 
> 作者你好，能提供下qq吗

你日志里都贴了
